---
title: "03_similarity"
author:
    - Thomas Naake^[Physikalisch-Technische Bundesanstalt, Bundesallee 100, 38116 Braunschweig, Germany]
fig_width: 15
fig_height: 10
fontsize: 12pt
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: TRUE
    theme: united
    number_sections: true
    highlight: tango
---

```{r env, include=FALSE, echo=FALSE, cache=FALSE}
suppressPackageStartupMessages(library("MsQuality"))
suppressPackageStartupMessages(library("Spectra"))
knitr::opts_knit$set(root.dir = "~/Documents/GitHub/MsCoreSys_metabolomics_ringtrial")
```

# Create Spectra object

Get all mzML files.
```{r}
## lab_Bindila
bindila_metab_neg <- list.files(
    "data/lab_Bindila/AG_Bindila_MSCoreSys_ringtrial_Negative_mode_QC_Raw_file_280425/mzML/",
    pattern = "[.]mzML", full.names = TRUE)
bindila_metab_neg_mzML <- list.files(
    "data/lab_Bindila/AG_Bindila_MSCoreSys_ringtrial_Negative_mode_QC_Raw_files_mzML/",
    pattern = "[.]mzML", full.names = TRUE)
bindila_metab_pos <- list.files(
    "data/lab_Bindila/AG_Bindila_MSCoreSys_ringtrial_Positive_mode_QC_Raw_file_280425/mzML/",
    pattern = "[.]mzML", full.names = TRUE)
bindila_metab_pos_mzML <- list.files(
    "data/lab_Bindila/AG_Bindila_MSCoreSys_ringtrial_Positive_mode_QC_Raw_files_mzML/",
    pattern = "[.]mzML", full.names = TRUE)

## lab_Hopf
hopf_lipid_neg <- list.files(
    "data/lab_Hopf/Hopf_lipidomic_neg/final/mzML/",
    pattern = "[.]mzML", full.names = TRUE)
hopf_lipid_pos <- list.files(
    "data/lab_Hopf/Hopf_lipidomic_pos/final/mzML/",
    pattern = "[.]mzML", full.names = TRUE)
hopf_metab_neg <- list.files(
    "data/lab_Hopf/Hopf_small_metabolites_pos_neg/neg/mzML/",
    pattern = "[.]mzML", full.names = TRUE)
hopf_metab_pos <- list.files(
    "data/lab_Hopf/Hopf_small_metabolites_pos_neg/pos/mzML/",
    pattern = "[.]mzML", full.names = TRUE)

## lab_Poschet
poschet_metab <- list.files(
    "data/lab_Poschet//mzML/",
    pattern = "[.]mzML", full.names = TRUE)

## lab_Schmidlin
schmidlin_metab_wiff <- list.files(
    "data/lab_Schmidlin/mzML_from_wiff/",
    pattern = "[.]mzML", full.names = TRUE)
schmidlin_metab_wiff2 <- list.files(
    "data/lab_Schmidlin/mzML_from_wiff2/",
    pattern = "[.]mzML", full.names = TRUE)
```

Create `Spectra` object.

```{r}
all_mzML_files <- c(
    ## lab_Bindila
    bindila_metab_neg, 
    bindila_metab_pos, 
    ## do not load the mzML files 
    ##bindila_metab_neg_mzML, 
    ##bindila_metab_pos_mzML,

    ## lab_Hopf
    hopf_lipid_neg, hopf_lipid_pos, hopf_metab_neg, hopf_metab_pos,
    
    ## lab_Poschet
    poschet_metab,

    ## lab_Schmidlin
    schmidlin_metab_wiff, schmidlin_metab_wiff2
)
sps <- Spectra(all_mzML_files, backend = MsBackendMzR(), BPPARAM = SerialParam())


## lab_Poschet
# poschet_metab <- poschet_metab[1]
# 
# be <- backendInitialize(ChromBackendMzR(),
#     files = poschet_metab,
#     BPPARAM = SerialParam()
# )
# 
# chrom <- Chromatograms(be)
# productMz_chrom <- sort(unique(productMz(chrom)))
# precursorMz_chrom <- sort(unique(precursorMz(chrom)))
# chrom$rtime ## 55-1627 events per entry
# 
# sps <- Spectra(poschet_metab, backend = MsBackendMzR(), BPPARAM = SerialParam())
# intensity(chrom[67094,])
# chrom <- chrom[1:10,]
# chrom$precursorMz
```

# Calculate similarity

```{r}
files <- sps$dataOrigin |>
    unique()
files_combn <- combn(files, m = 2)

similarity_mat_l <- list(
    max = Matrix::Matrix(NA, nrow = length(files), ncol = length(files), 
        dimnames = list(files, files)),
    mean = Matrix::Matrix(NA, nrow = length(files), ncol = length(files), 
        dimnames = list(files, files))
)

for (comb_col_i in seq_len(ncol(files_combn))) {
    
    ## obtain the file names of comb_col_i and assign to row_i and col_i
    row_i <- files_combinations[1, comb_col_i]
    col_i <- files_combinations[2, comb_col_i]
    
    ## 
    
}

similarity_ndotproduct <- compareSpectra(sps[1:20], MAPFUN = joinPeaks, 
    type = "outer", FUN = MsCoreUtils::ndotproduct, ppm = 20)
compareSpectra(sps[1:10], MAPFUN = joinPeaksGnps, FUN = MsCoreUtils::gnps, ppm = 20)

``` 

Save the data.

```{r}
```


